name: Golang API Workflow
run-name: Triggered by ${{ github.actor }}


on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - edited

jobs:
  building_and_validating_code:
    name: Build Code
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: checkout_code
        uses: actions/checkout@v4

      - name: Debug Info
        run: |
          echo "Running on branch: $GITHUB_REF"
          echo "Event: $GITHUB_EVENT_NAME"
          ls -la

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build
        run: |
          go mod tidy
          go build -v ./...
      
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  build_and_push_docker_image:
    name: Build Docker Image
    needs: building_and_validating_code
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: checkout_code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.API_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/golang:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/golang:${{ github.sha }}
